/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package User;

import java.awt.Desktop;
import java.io.File;
import java.io.InputStream;
import javax.swing.JOptionPane;

/**
 *
 * @author USER
 */
public class MainUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainUI.class.getName());

    /**
     * Creates new form MainUI
     */
    public MainUI() {
        initComponents();
        setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnSignIn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        MItemUserManual = new javax.swing.JMenuItem();
        MItemClose = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        MItemSignIn = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LifeCare Hub");
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(0, 102, 204));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 70)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 102));
        jLabel1.setText("LifeCare Hub");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 120, -1, -1));

        btnSignIn.setBackground(new java.awt.Color(153, 204, 255));
        btnSignIn.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        btnSignIn.setForeground(new java.awt.Color(0, 0, 102));
        btnSignIn.setText("Sign In");
        btnSignIn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 102), 5, true));
        btnSignIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignInActionPerformed(evt);
            }
        });
        getContentPane().add(btnSignIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 360, 180, 70));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 102));
        jLabel3.setText("Welcome to LifeCare Hub ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 230, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 102));
        jLabel4.setText("Your Digital Healthcare Assistant");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 280, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img1.jpg"))); // NOI18N
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 204), 5));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -30, 1360, 690));

        jMenuBar1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 204), 5));

        jMenu1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 204), 5));
        jMenu1.setText("Help");

        MItemUserManual.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        MItemUserManual.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        MItemUserManual.setText("User Manual");
        MItemUserManual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MItemUserManualActionPerformed(evt);
            }
        });
        jMenu1.add(MItemUserManual);

        MItemClose.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        MItemClose.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        MItemClose.setText("Close");
        MItemClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MItemCloseActionPerformed(evt);
            }
        });
        jMenu1.add(MItemClose);

        jMenuBar1.add(jMenu1);

        jMenu2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 204), 5));
        jMenu2.setText("Login");

        MItemSignIn.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        MItemSignIn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        MItemSignIn.setText("Sign In");
        MItemSignIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MItemSignInActionPerformed(evt);
            }
        });
        jMenu2.add(MItemSignIn);

        jMenuBar1.add(jMenu2);

        jMenu3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 204), 5));
        jMenu3.setText("More");
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSignInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignInActionPerformed
        // Sign In Button Option attrive at Login portal
        LoginUI Log= new LoginUI();
        Log.setVisible(true);
    }//GEN-LAST:event_btnSignInActionPerformed

    private void MItemCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MItemCloseActionPerformed
        // Close Menu Item
        System.exit(0);
    }//GEN-LAST:event_MItemCloseActionPerformed

    private void MItemUserManualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MItemUserManualActionPerformed
        // User Manual Menu Item
        try {
            InputStream is = getClass().getResourceAsStream("/UserManual.docx");

            if (is == null) {
                JOptionPane.showMessageDialog(this, "User Manual not found !", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            File tempFile = File.createTempFile("UserManual", ".docx");
            tempFile.deleteOnExit();

            java.nio.file.Files.copy(is, tempFile.toPath(), java.nio.file.StandardCopyOption.REPLACE_EXISTING);

            Desktop.getDesktop().open(tempFile);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Unable to open User Manual", "Error", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }//GEN-LAST:event_MItemUserManualActionPerformed

    private void MItemSignInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MItemSignInActionPerformed
        // Sign In Button Option attrive at Login portal
        LoginUI Log= new LoginUI();
        Log.setVisible(true);
    }//GEN-LAST:event_MItemSignInActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MItemClose;
    private javax.swing.JMenuItem MItemSignIn;
    private javax.swing.JMenuItem MItemUserManual;
    private javax.swing.JButton btnSignIn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
