/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package User;

import java.awt.Desktop;
import java.io.File;
import java.io.InputStream;
import javax.swing.JOptionPane;

/**
 *
 * @author USER
 */
public class OperationsUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(OperationsUI.class.getName());

    /**
     * Creates new form OperationsUI
     */
    public OperationsUI() {
        initComponents();
        setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnPatientRegist = new javax.swing.JButton();
        btnEmergencyHandling = new javax.swing.JButton();
        btnPHistory = new javax.swing.JButton();
        btnPatientDetails = new javax.swing.JButton();
        btnSignOut = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnCheckOut = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        MItemUserManual = new javax.swing.JMenuItem();
        MItemClose = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        MItemPatientRegistration = new javax.swing.JMenuItem();
        MItemEmergency = new javax.swing.JMenuItem();
        MItemPatientDetails = new javax.swing.JMenuItem();
        MItemCheckOut = new javax.swing.JMenuItem();
        MItemPatientHistory = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Home Portal");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnPatientRegist.setBackground(new java.awt.Color(204, 255, 255));
        btnPatientRegist.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnPatientRegist.setForeground(new java.awt.Color(0, 0, 102));
        btnPatientRegist.setText("Patient Registration ");
        btnPatientRegist.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 204, 255), 5));
        btnPatientRegist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPatientRegistActionPerformed(evt);
            }
        });
        getContentPane().add(btnPatientRegist, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, 530, 110));

        btnEmergencyHandling.setBackground(new java.awt.Color(204, 255, 255));
        btnEmergencyHandling.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnEmergencyHandling.setForeground(new java.awt.Color(0, 0, 102));
        btnEmergencyHandling.setText("Emergency Handling");
        btnEmergencyHandling.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 204, 255), 5));
        btnEmergencyHandling.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmergencyHandlingActionPerformed(evt);
            }
        });
        getContentPane().add(btnEmergencyHandling, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, 260, 110));

        btnPHistory.setBackground(new java.awt.Color(204, 255, 255));
        btnPHistory.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnPHistory.setForeground(new java.awt.Color(0, 0, 102));
        btnPHistory.setText("Patient History ");
        btnPHistory.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 204, 255), 5));
        btnPHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPHistoryActionPerformed(evt);
            }
        });
        getContentPane().add(btnPHistory, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 340, 260, 110));

        btnPatientDetails.setBackground(new java.awt.Color(204, 255, 255));
        btnPatientDetails.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnPatientDetails.setForeground(new java.awt.Color(0, 0, 102));
        btnPatientDetails.setText("Patient Details");
        btnPatientDetails.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 204, 255), 5));
        btnPatientDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPatientDetailsActionPerformed(evt);
            }
        });
        getContentPane().add(btnPatientDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 220, 260, 110));

        btnSignOut.setBackground(new java.awt.Color(204, 255, 255));
        btnSignOut.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnSignOut.setForeground(new java.awt.Color(0, 0, 102));
        btnSignOut.setText("Sign Out");
        btnSignOut.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 204, 255), 5));
        btnSignOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignOutActionPerformed(evt);
            }
        });
        getContentPane().add(btnSignOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 460, 530, 50));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 102));
        jLabel1.setText("Home Portal");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, -1, -1));

        btnCheckOut.setBackground(new java.awt.Color(204, 255, 255));
        btnCheckOut.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnCheckOut.setForeground(new java.awt.Color(0, 0, 102));
        btnCheckOut.setText("Check-Out");
        btnCheckOut.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 204, 255), 5));
        btnCheckOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckOutActionPerformed(evt);
            }
        });
        getContentPane().add(btnCheckOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 340, 260, 110));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img4.jpg"))); // NOI18N
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 204), 5));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -30, -1, 580));

        jMenuBar1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 204), 5));

        jMenu1.setText("Help");

        MItemUserManual.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        MItemUserManual.setText("User Manual");
        MItemUserManual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MItemUserManualActionPerformed(evt);
            }
        });
        jMenu1.add(MItemUserManual);

        MItemClose.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        MItemClose.setText("Close");
        MItemClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MItemCloseActionPerformed(evt);
            }
        });
        jMenu1.add(MItemClose);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Options");

        MItemPatientRegistration.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        MItemPatientRegistration.setText("Patient Registration");
        MItemPatientRegistration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MItemPatientRegistrationActionPerformed(evt);
            }
        });
        jMenu2.add(MItemPatientRegistration);

        MItemEmergency.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        MItemEmergency.setText("Emergency Handling");
        MItemEmergency.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MItemEmergencyActionPerformed(evt);
            }
        });
        jMenu2.add(MItemEmergency);

        MItemPatientDetails.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        MItemPatientDetails.setText("Patient Details");
        MItemPatientDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MItemPatientDetailsActionPerformed(evt);
            }
        });
        jMenu2.add(MItemPatientDetails);

        MItemCheckOut.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        MItemCheckOut.setText("Check-Out");
        MItemCheckOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MItemCheckOutActionPerformed(evt);
            }
        });
        jMenu2.add(MItemCheckOut);

        MItemPatientHistory.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        MItemPatientHistory.setText("Patient History");
        MItemPatientHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MItemPatientHistoryActionPerformed(evt);
            }
        });
        jMenu2.add(MItemPatientHistory);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPatientRegistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPatientRegistActionPerformed
        // Click Patient Registration Button and go to Patient Registration Portal
        PatientRegistrationUI PR= new PatientRegistrationUI();
        PR.setVisible(true);
    }//GEN-LAST:event_btnPatientRegistActionPerformed

    private void btnEmergencyHandlingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmergencyHandlingActionPerformed
        // Click Emergency Handling Button and go to Emergency Handling Portal
        EmergencyHandlingUI EH= new EmergencyHandlingUI();
        EH.setVisible(true);
    }//GEN-LAST:event_btnEmergencyHandlingActionPerformed

    private void btnPHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPHistoryActionPerformed
        // Click Patient History Retrieval Button and go to Patient History Retrieval Portal
        PatientHistoryRetrievalUI PHR= new PatientHistoryRetrievalUI();
        PHR.setVisible(true);
    }//GEN-LAST:event_btnPHistoryActionPerformed

    private void btnPatientDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPatientDetailsActionPerformed
        // Click Patient Details Button and go to Patient Details Portal
        PatientDetailsUI PD= new PatientDetailsUI();
        PD.setVisible(true);
    }//GEN-LAST:event_btnPatientDetailsActionPerformed

    private void btnSignOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignOutActionPerformed
        // Click Patient Registration Button and go to Patient Registration Portal
        MainUI MUI= new MainUI();
        MUI.setVisible(true);
    }//GEN-LAST:event_btnSignOutActionPerformed

    private void btnCheckOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckOutActionPerformed
        // Click Patient Check-Out Button and go to Patient Check-Out Portal
        CheckOutUI CHOUI= new CheckOutUI();
        CHOUI.setVisible(true);
    }//GEN-LAST:event_btnCheckOutActionPerformed

    private void MItemCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MItemCloseActionPerformed
        // Close Menu Item
        System.exit(0);
    }//GEN-LAST:event_MItemCloseActionPerformed

    private void MItemUserManualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MItemUserManualActionPerformed
        // User Manual Menu Item
        try {
            InputStream is = getClass().getResourceAsStream("/UserManual.docx");

            if (is == null) {
                JOptionPane.showMessageDialog(this, "User Manual not found in !", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            File tempFile = File.createTempFile("UserManual", ".docx");
            tempFile.deleteOnExit();

            java.nio.file.Files.copy(is, tempFile.toPath(), java.nio.file.StandardCopyOption.REPLACE_EXISTING);

            Desktop.getDesktop().open(tempFile);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Unable to open User Manual", "Error", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }//GEN-LAST:event_MItemUserManualActionPerformed

    private void MItemPatientDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MItemPatientDetailsActionPerformed
        // Click Patient Details Menu Item and go to Patient Details Portal
        PatientDetailsUI PD= new PatientDetailsUI();
        PD.setVisible(true);
    }//GEN-LAST:event_MItemPatientDetailsActionPerformed

    private void MItemPatientHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MItemPatientHistoryActionPerformed
        // Click Patient History Retrieval Menu Item and go to Patient History Retrieval Portal
        PatientHistoryRetrievalUI PHR= new PatientHistoryRetrievalUI();
        PHR.setVisible(true);
    }//GEN-LAST:event_MItemPatientHistoryActionPerformed

    private void MItemPatientRegistrationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MItemPatientRegistrationActionPerformed
        // Click Patient Registration Menu Item and go to Patient Registration Portal
        PatientRegistrationUI PR= new PatientRegistrationUI();
        PR.setVisible(true);
    }//GEN-LAST:event_MItemPatientRegistrationActionPerformed

    private void MItemEmergencyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MItemEmergencyActionPerformed
        // Click Emergency Handling Menu Item and go to Emergency Handling Portal
        EmergencyHandlingUI EH= new EmergencyHandlingUI();
        EH.setVisible(true);
    }//GEN-LAST:event_MItemEmergencyActionPerformed

    private void MItemCheckOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MItemCheckOutActionPerformed
        // Click Patient Check-Out Menu Item and go to Patient Check-Out Portal
        CheckOutUI CHOUI= new CheckOutUI();
        CHOUI.setVisible(true);
    }//GEN-LAST:event_MItemCheckOutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new OperationsUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MItemCheckOut;
    private javax.swing.JMenuItem MItemClose;
    private javax.swing.JMenuItem MItemEmergency;
    private javax.swing.JMenuItem MItemPatientDetails;
    private javax.swing.JMenuItem MItemPatientHistory;
    private javax.swing.JMenuItem MItemPatientRegistration;
    private javax.swing.JMenuItem MItemUserManual;
    private javax.swing.JButton btnCheckOut;
    private javax.swing.JButton btnEmergencyHandling;
    private javax.swing.JButton btnPHistory;
    private javax.swing.JButton btnPatientDetails;
    private javax.swing.JButton btnPatientRegist;
    private javax.swing.JButton btnSignOut;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
